extends Control

var aTxt = []
var iC = 0
var bFirst = true
var bPausing = false
var bPaused = true

func _ready():
	$PanelContainer/VBoxContainer/TabContainer.current_tab = 0
	get_tree().set_auto_accept_quit(false)

func _notification(what):
	if what == NOTIFICATION_WM_CLOSE_REQUEST:
		if GDSync.is_active():
			if Globals.bStarted:
				GDSync.call_func(Globals.playerQuit, [Globals.iMyPN])

			GDSync.quit()
		else:
			get_tree().quit()

func _process(_delta):
	if not bPaused:
		if not bPausing and not TTS.is_speaking():
			if Globals.optVoice > 0:
				callSpeak()

func _on_VBoxContainer_draw():
	if bFirst:
		_on_TabContainer_tab_selected(0)
		bFirst = false

func _on_TabContainer_tab_selected(tab):
	if not bFirst:
		$SFX.stream = Globals.sfx_click
		$SFX.play()

	aTxt = []
	iC = 0

	if Globals.optVoice > 0:
		match tab:
			0:
				aTxt.append("Welcome to Space Colony Cheeses 2 - The Computer Game")
				aTxt.append("P5")
				aTxt.append("The colonisation of space is going smoothly.")
				aTxt.append("P1")
				aTxt.append("Spaceships fly on schedule from colony to colony, bearing the imports and exports of dozens of planets.")
				aTxt.append("P1")
				aTxt.append("But most of the trade is centred on necessities.")
				aTxt.append("P1")
				aTxt.append("There's no way to send a tasteful Christmas gift of assorted cheeses and beef sausages to a loved one on another planet.")
				aTxt.append("P1")
				aTxt.append("You've been assigned to change all that.")
				aTxt.append("P1")
				aTxt.append("You are in charge of colonizing a newly discovered world, Bos 4.")
				aTxt.append("P1")
				aTxt.append("Bos 4 is similar in most ways to Bos 3, from the Space Colony Cheeses board game, but you cannot build Spaceports here, as the natives won’t allow it, and it has less sunlight, so you cannot use Solar Power!")
				aTxt.append("P1")
				aTxt.append("Instead the boffins have perfected Portals for travelling to Bos 3, which does have Spaceports, and they have also discovered that Bos 4 has an almost unlimited amount of Yapthalene Crystals, which come in four funky colours.")
				aTxt.append("P1")
				aTxt.append("Green, Orange, Sky Blue and Yellow.")
				aTxt.append("P1")
				aTxt.append("that can be grown, and mined, in special areas called Crystal Mines.")
				aTxt.append("P1")
				aTxt.append("Your task is to build a thriving, profitable, dairy colony using these crystals for power, as well as geothermal energy from certain areas of the planet, basically anywhere you can see steam rising from the ground is where you can place your Geothermal Powerplants.")
				aTxt.append("P1")
				aTxt.append("You must choose when, where and how to expand.")
				aTxt.append("P1")
				aTxt.append("You'll have to balance the need for money making against the need for energy production.")
				aTxt.append("P1")
				aTxt.append("If you can afford it, you may want to expand into other dairy products, increase your storage capacity, or just harass the competition with endless lawsuits.")
				aTxt.append("P1")
				aTxt.append("The choices, and the responsibility, are yours.")
				aTxt.append("P5")
				aTxt.append("Finally, last year saw one of the biggest nanotech breakthroughs in history, the creation of a special breed of Cow.")
				aTxt.append("P1")
				aTxt.append("The Nano Cow.")
				aTxt.append("P1")
				aTxt.append("These Nano Cows are invisible to the human eye, but can be milked and slaughtered using special machinery.")
				aTxt.append("P1")
				aTxt.append("To populate your pastures with these amazing creatures, you firstly build a Pasture Dome, then you release the special Nano Fluid onto the crystals and, in a few short minutes, there will literally be billions of Nano Cows living and breeding in your Pasture Dome and spreading to your Barns, with nothing for you to do but ensure the modules are maintained and, of course, reap the rewards.")
				aTxt.append("P5")
				aTxt.append("Space Colony Cheeses 2 is a light-hearted, non-violent game for 2 to 4 Players, based on Space Colony Cheeses, a board game by The Mad Game Designer.")
			1:
				aTxt.append("The ultimate goal of the game is to make money.")
				aTxt.append("P1")
				aTxt.append("You do this by adding modules to your colony.")
				aTxt.append("P1")
				aTxt.append("Some modules generate dollars, and some do not, but all can be useful to the colony.")
				aTxt.append("P1")
				aTxt.append("Each Player begins the game with one hundred dollars.")
				aTxt.append("P5")
				aTxt.append("You roll a dice to see who goes first.")
				aTxt.append("P1")
				aTxt.append("Each colony MUST begin with a Startup module.")
				aTxt.append("P1")
				aTxt.append("A colony CAN ONLY be started in one of the four coloured Quadrants of the Board, that is, ONLY ONE Player can start in any one Quadrant and a Player MAY NOT start multiple colonies.")
				aTxt.append("P5")
				aTxt.append("The map is unlike most maps you will have seen.")
				aTxt.append("P1")
				aTxt.append("There are two kinds of grid units, squares and octagons.")
				aTxt.append("P1")
				aTxt.append("A square has only four neighbours, while an octagon has eight.")
				aTxt.append("P1")
				aTxt.append("This can be important when arranging your modules.")
				aTxt.append("P5")
				aTxt.append("The map has two kinds of features, Geothermal Steam and Lush Pastures.")
				aTxt.append("P1")
				aTxt.append("Geothermal Steam can be found anywhere that you see steam rising from the ground and are the ONLY places that you can build Geothermal Plants.")
				aTxt.append("P1")
				aTxt.append("Lush Pastures have grass growing on them, and give a bonus to any Barns that are built on them.")
				aTxt.append("P5")
				aTxt.append("Bos 4 is an anomaly.")
				aTxt.append("P1")
				aTxt.append("Earth-type plants grow well here, but the atmosphere does not retain oxygen.")
				aTxt.append("P1")
				aTxt.append("Thus, there is plenty of grassland for your Nano Cows to munch on, but everything must be enclosed in modular domes with artificial atmospheres.")
				aTxt.append("P5")
				aTxt.append("All of these modules must be connected to each other.")
				aTxt.append("P1")
				aTxt.append("Only the Startup module can stand alone.")
				aTxt.append("P1")
				aTxt.append("Each module requires 1 energy unit per turn.")
				aTxt.append("P1")
				aTxt.append("Modules that are short of energy cannot function and produce nothing.")
				aTxt.append("P1")
				aTxt.append("You can, however, build a module with no energy source, and add one later.")
				aTxt.append("P5")
				aTxt.append("Food is not a problem for your colony, since that is exactly what you are producing.")
				aTxt.append("P1")
				aTxt.append("As your colony makes commodities, they are kept track of on the scoreboard, as is your current bank balance.")
			2:
				aTxt.append("Game Sequence.")
				aTxt.append("P5")
				aTxt.append("Step 1. Colonies with a Construction module can move any one of their own modules currently placed on the map.")
				aTxt.append("P1")
				aTxt.append(" Such a move will cost half of the original cost of the module.")
				aTxt.append("P1")
				aTxt.append(" Beware that you must have enough money in your bank to move the most expensive of your placed modules.")
				aTxt.append("P5")
				aTxt.append("Step 2. Each colony can add up to a maximum of 3 new modules, if it has enough money in the bank and space on the map.")
				aTxt.append("P5")
				aTxt.append("Step 3. Each colony rolls a dice.")
				aTxt.append("P1")
				aTxt.append("If it comes up a 1, then a new disease has started in the herds of that colony.")
				aTxt.append("P1")
				aTxt.append("Yes, Nano Cows can get sick as well.")
				aTxt.append("P1")
				aTxt.append("One of the Barn modules of that colony MUST now be marked as SICK.")
				aTxt.append("P1")
				aTxt.append("That Barn is now unable to produce anything until the disease is cured.")
				aTxt.append("P1")
				aTxt.append("A colony CANNOT have more than 4 diseases at once, so any others that crop up are ignored.")
				aTxt.append("P1")
				aTxt.append("If the colony has 4 diseases at one time, then it cannot sell anything except Leather and Manure.")
				aTxt.append("P5")
				aTxt.append("Step 4. Each colony calculates its energy production and then subtracts the energy needs of all the other modules.")
				aTxt.append("P1")
				aTxt.append("If there is not enough energy to go around, modules MUST be marked as OFFLINE, which denotes an energy shortage, until there is enough energy available to power them again.")
				aTxt.append("P1")
				aTxt.append("An energy-producing module cannot be marked as OFFLINE, and any surplus energy is lost.")
				aTxt.append("P5")
				aTxt.append("Step 5. Each colony now calculates its commodity production from each Barn next to a Processing Plant, and allocates it to the eight available commodities.")
				aTxt.append("P5")
				aTxt.append("Milk, Cream, Butter, Ice Cream, Cheese, Beef, Leather and Manure.")
				aTxt.append("P5")
				aTxt.append("A colony CANNOT make more of a particular commodity than it has storage for.")
				aTxt.append("P1")
				aTxt.append("The maximum storage capacity of any product is ten.")
				aTxt.append("P1")
				aTxt.append("If there is no storage space available for a commodity, then it cannot be made.")
				aTxt.append("P5")
				aTxt.append("Step 6. Each colony now rolls two dice, and a RANDOM EVENT is generated.")
				aTxt.append("P1")
				aTxt.append("The colony must follow all instructions for the RANDOM EVENT.")
				aTxt.append("P1")
				aTxt.append("Note that should the colony be allowed to change a commodity price, then the change will be applied in Step eight.")
				aTxt.append("P1")
				aTxt.append("Also note that commodity prices can never fall below zero.")
				aTxt.append("P5")
				aTxt.append("Step 7. Each colony that has a functioning Portal, a functioning Store, and at least one stored commodity of Cheese and one of Beef, can now sell GIFT BOXES.")
				aTxt.append("P5")
				aTxt.append("If a GIFT BOX is sold, then the stored amounts of Cheese and Beef will be reduced accordingly.")
				aTxt.append("P5")
				aTxt.append("Step 8. A dice is now rolled for each commodity to set the price for the current turn.")
				aTxt.append("P1")
				aTxt.append("Each colony with a functional Portal can now sell as many of that commodity as they want, adjusting the price by the results of their RANDOM EVENT roll as needed.")
				aTxt.append("P5")
				aTxt.append("Step 9. Now, all income from Startups, Cheese Labs, and Sausage Labs is added to the bank balance of the colony, and Law Offices file lawsuits, if required.")
				aTxt.append("P5")
				aTxt.append("Step 10. A dice is now rolled for each diseased Barn or Megabarn.")
				aTxt.append("P1")
				aTxt.append("If it comes up five or six, then the disease has been cured.")
				aTxt.append("P1")
				aTxt.append("If the disease is cured, the Barn, or Megabarn, is no longer marked as SICK.")
				aTxt.append("P5")
				aTxt.append("Step 11. Finally, all stored commodities, except for Leather and Manure, are reset to zero.")
			3:
				aTxt.append("Colony Modules Part 1.")
				aTxt.append("P5")
				aTxt.append("Start-Up Modules also known as Crystal Mines.")
				aTxt.append("P5")
				aTxt.append("You are allowed one of these modules at a cost of twenty dollars.")
				aTxt.append("P1")
				aTxt.append("They produce income of two dollars and produce two units of energy.")
				aTxt.append("P5")
				aTxt.append("These MUST be the first modules built.")
				aTxt.append("P1")
				aTxt.append("However, they are quite expensive as they not only generate their own energy but also a small amount of money.")
				aTxt.append("P5")
				aTxt.append("Crystal Powerplant Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed three of these modules at a Cost of five dollars each.")
				aTxt.append("P1")
				aTxt.append("They produce three units of energy.")
				aTxt.append("P5")
				aTxt.append("These are the least expensive, and least powerful, energy source.")
				aTxt.append("P5")
				aTxt.append("Geothermal Powerplant Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed four of these modules at a cost of ten dollars each.")
				aTxt.append("P1")
				aTxt.append("They produce six units of energy.")
				aTxt.append("P5")
				aTxt.append("These produce more energy than the Crystal Powerplant, but can only be built on board locations with Geothermal Steam.")
				aTxt.append("P5")
				aTxt.append("Hub Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed four of these modules at a cost of 5 dollars each.")
				aTxt.append("P5")
				aTxt.append("These are special connector modules.")
				aTxt.append("P1")
				aTxt.append("Any module adjacent to a Hub is considered adjacent to any other modules that the Hub is also adjacent to.")
				aTxt.append("P1")
				aTxt.append("Note that Hub modules use no energy.")
			4:
				aTxt.append("Colony Modules Part 2.")
				aTxt.append("P5")
				aTxt.append("Storage Modules for Butter, Cream, Ice Cream, Manure and Milk.")
				aTxt.append("P5")
				aTxt.append("You are allowed one of these modules for each commodity at a cost of five dollars each.")
				aTxt.append("P1")
				aTxt.append("They require one unit of energy.")
				aTxt.append("P5")
				aTxt.append("These modules can store up to ten units of Butter, Cream, Ice Cream, Manure or Milk, which can be sold, along with the other commodities, at a Portal.")
				aTxt.append("P1")
				aTxt.append("All commodity Storage modules must be adjacent to a Processing Plant.")
				aTxt.append("P1")
				aTxt.append("Note that, at the end of each turn, any remaining stored commodities, except Leather and Manure, spoil and MUST be discarded with the relevant inventory dropping to zero.")
				aTxt.append("P5")
				aTxt.append("Storage Modules for Beef, Cheese and Leather.")
				aTxt.append("P5")
				aTxt.append("You are allowed one of these modules for each commodity at a cost of five dollars each.")
				aTxt.append("P1")
				aTxt.append("They require one unit of energy.")
				aTxt.append("P5")
				aTxt.append("These modules can store up to ten units of Beef, Cheese or Leather, which can be sold, along with the other commodities, at a Portal.")
				aTxt.append("P1")
				aTxt.append("All commodity Storage modules must be adjacent to a Processing Plant.")
				aTxt.append("P1")
				aTxt.append("Note that, at the end of each turn, any remaining stored commodities, except Leather and Manure, spoil and MUST be discarded with the relevant inventory dropping to zero.")
				aTxt.append("P5")
				aTxt.append("Barn Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed seven of these modules at a Cost of ten dollars each.")
				aTxt.append("P1")
				aTxt.append("They require one unit of energy and generate an output of five or seven commodity units.")
				aTxt.append("P5")
				aTxt.append("These support one herd of Nano cows, including all required feeding and milking equipment.")
				aTxt.append("P1")
				aTxt.append("They produce five commodity units per turn, or seven if built on a Lush Pasture.")
				aTxt.append("P1")
				aTxt.append("Note that Barns MUST be adjacent to a Processing Plant.")
				aTxt.append("P5")
				aTxt.append("Megabarn Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed one of these modules at a cost of twemnty dollars.")
				aTxt.append("P1")
				aTxt.append("They require one unit of energy and generate an output of ten or fourteen commodity units.")
				aTxt.append("P5")
				aTxt.append("These count as two Barn modules for commodity output, and as one Barn module for energy usage.")
			5:
				aTxt.append("Colony Modules Part 3.")
				aTxt.append("P5")
				aTxt.append("Processing Plant Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed two of these modules at a cost of ten dollars each.")
				aTxt.append("P1")
				aTxt.append("They require two units of energy.")
				aTxt.append("P5")
				aTxt.append("These turn the output from the herd into Beef, Butter, Cheese, Cream, Ice Cream, Leather, Manure or Milk.")
				aTxt.append("P1")
				aTxt.append("There is no limit on how many units of each commodity a Processing Plant can make, except that there must be room in the Storage modules for everything.")
				aTxt.append("P1")
				aTxt.append("Note that anything that will not fit in a Storage module is lost and a Processing Plant requires two units of energy per turn, not the usual one.")
				aTxt.append("P5")
				aTxt.append("Pasture Dome Modules.")
				aTxt.append("You are allowed three of these modules at a cost of  five dollars each.")
				aTxt.append("P1")
				aTxt.append("They require one unit of energy.")
				aTxt.append("P5")
				aTxt.append("These are enclosed grazing areas, which must be adjacent to a Barn or Megabarn.")
				aTxt.append("P1")
				aTxt.append("Bad things can happen if there is not at least one Pasture Dome for each three Barns worth of Nano Cows, count one Megabarn as two Barns.")
				aTxt.append("P5")
				aTxt.append("Catalog Store Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed one of these modules at a cost of ten dollars.")
				aTxt.append("P1")
				aTxt.append("They produce $10 per turn and require 1 unit of energy.")
				aTxt.append("P5")
				aTxt.append("These allow the selling of tasteful gift boxes of assorted Cheeses, Beef Sausages, and flavourless crackers, usually at higher prices than the Cheese and Beef alone would fetch.")
				aTxt.append("P1")
				aTxt.append("A Catalog Store CANNOT function unless there is a working Portal and at least one stored unit each of Cheese and Beef.")
				aTxt.append("P1")
				aTxt.append("Gift boxes are made of one Cheese and one Beef unit each, and usually sell for ten dollars.")
				aTxt.append("P5")
				aTxt.append("Habitation Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed one of these modules at a Cost of five dollars.")
				aTxt.append("P1")
				aTxt.append("They require one unit of energy.")
				aTxt.append("P5")
				aTxt.append("These are living spaces for the workers of the colony, and are required for the colony to exceed twelve modules.")
				aTxt.append("P1")
				aTxt.append("In other words, the thirteenth module MUST be a Habitation module.")
				aTxt.append("P1")
				aTxt.append("Should this module be deprived of energy, then no more modules may be placed until it is functional again.")
			6:
				aTxt.append("Colony Modules Part 4.")
				aTxt.append("P5")
				aTxt.append("Construction Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed one of these modules at a Cost of ten dollars.")
				aTxt.append("P1")
				aTxt.append("They require one unit of energy.")
				aTxt.append("P5")
				aTxt.append("These reduce the cost of new module construction by $one dollar per module, and allow the movement of one existing module, per turn, to another location.")
				aTxt.append("P1")
				aTxt.append("However, this movement is not free, and costs half of the original purchase price.")
				aTxt.append("P1")
				aTxt.append("Fractions will be dropped.")
				aTxt.append("P5")
				aTxt.append("Veterinary Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed one of these modules at a Cost of ten dollars.")
				aTxt.append("P1")
				aTxt.append("They require one unit of energy.")
				aTxt.append("P5")
				aTxt.append("These are packed full of the best Nano-Veterinarians in the Galaxy and give the colony a second chance to overcome diseases.")
				aTxt.append("P5")
				aTxt.append("Laboratory Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed two of these modules, one each of Cheese and Sausages, at a Cost of ten dollars each.")
				aTxt.append("P1")
				aTxt.append("They generate four dollars per turn and require one unit of energy.")
				aTxt.append("P5")
				aTxt.append("These generate the money through research into new flavours of Cheeses or Sausages, and will generate money whether there is a functional Portal or not.")
				aTxt.append("P5")
				aTxt.append("Veterinary Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed one of these modules at a Cost of fifteen dollars.")
				aTxt.append("P1")
				aTxt.append("They require 1one unit of energy.")
				aTxt.append("P5")
				aTxt.append("These are full of greedy and well paid corporate lawyers who are eager to sue the udders off the competition.")
				aTxt.append("P1")
				aTxt.append("Each turn, a colony can choose to file a suit against one other colony for infringement of grazing rights, contract violations, a strawberry tort, or whatever else the legal eagles can think of.")
				aTxt.append("P1")
				aTxt.append("All such lawsuits are decided by the roll of a dice.")
				aTxt.append("P1")
				aTxt.append("If it comes up one to four, it is multiplied by ten, and that is how many dollars the colony receives in reparations.")
				aTxt.append("P1")
				aTxt.append("If it comes up five, the case was dismissed, and a six means the court found for the other colony, who must be paid twenty five dollars in damages.")
				aTxt.append("P1")
				aTxt.append("Note that a colony with less than fifty dollars in the bank CANNOT be sued.")
			7:
				aTxt.append("Colony Modules Part 5.")
				aTxt.append("P5")
				aTxt.append("Portal Modules.")
				aTxt.append("P5")
				aTxt.append("You are allowed one of these modules at a Cost of ten dollars.")
				aTxt.append("P1")
				aTxt.append("They require one unit of energy.")
				aTxt.append("P5")
				aTxt.append("These are required in order to trade with the rest of the Galaxy, via Bos three.")
				aTxt.append("P1")
				aTxt.append("Prices of the eight commodities are different each turn and for each colony.")
				aTxt.append("P1")
				aTxt.append("Each price is determined by a roll of the dice.")
				aTxt.append("P1")
				aTxt.append("The price of Leather can never be higher than three, and the price of Manure is always one.")
				aTxt.append("P1")
				aTxt.append("Note that Random Events can override these limits.")
			8:
				aTxt.append("Winning the game.")
				aTxt.append("P5")
				aTxt.append("The colony with the most money at the end of fifteen turns is the winner.")
				aTxt.append("P5")
				aTxt.append("If it is a tie, then you can shake hands and call it even, or roll the dice and decide to go to SUDDEN DEATH, where you have three extra rounds to try to beat your opposition.")
				aTxt.append("P1")
				aTxt.append("This can be repeated ad-infinitum, if you so desire, but has to be agreed to by ALL Players after every extra three rounds.")
				aTxt.append("P5")
				aTxt.append("GOOD LUCK!")
			9:
				aTxt.append("Keyboard and Mouse.")
				aTxt.append("P5")
				aTxt.append("The f one key displays this help. Press it again to close.")
				aTxt.append("P5")
				aTxt.append("The f two key displays the options menu. Press it again to close.")
				aTxt.append("P5")
				aTxt.append("The f three key stops any current speech.")
				aTxt.append("P5")
				aTxt.append("The w, a, s and d keys move the camera forwards, left, backwards and right.")
				aTxt.append("P5")
				aTxt.append("The down arrow makes the camera look down.")
				aTxt.append("P5")
				aTxt.append("The up arrow makes the camera look up.")
				aTxt.append("P5")
				aTxt.append("The mouse wheel increases and decreases the movement speed of the camera.")
				aTxt.append("P5")
				aTxt.append("If you hold the right mouse button and move the mouse, the camera will rotate around it's up axis.")
				aTxt.append("P5")
			10:
				aTxt.append("About and Credits.")
				aTxt.append("P5")
				aTxt.append("Space Colony Cheeses two is based on Space Colony Cheeses, a board game by The Mad Game Designer, also known as Michael Fischer.")
				aTxt.append("P5")
				aTxt.append("The models for the buildings were purchased from Turbosquid and were created by k vakling.")
				aTxt.append("P5")
				aTxt.append("The Background Images are from NASA and the European Space Agency.")
				aTxt.append("P5")
				aTxt.append("The Music was purchased from Arteria3D.")
				aTxt.append("P5")
				aTxt.append("The Sound Effects are by TBA.")
				aTxt.append("P5")
				aTxt.append("PBR Textures are from free p b r.")
				aTxt.append("P5")
				aTxt.append("The Particles are from the Particle Pack by Kenney.")
				aTxt.append("P5")
				aTxt.append("Multiplayer and the overall Theme are from the G D Sync plug in.")
				aTxt.append("P5")
				aTxt.append("We have also used the Universal Settings plug in from antz games.")
				aTxt.append("P5")
				aTxt.append("Copyright Spinalsoft AU 2025")

func _on_Button_pressed():
	$SFX.stream = Globals.sfx_click
	$SFX.play()

	if bPaused:
		bPaused = false
		$PanelContainer/VBoxContainer/PanelContainer/HBoxContainer/Button.text = "PAUSE"
	else:
		bPaused = true
		$PanelContainer/VBoxContainer/PanelContainer/HBoxContainer/Button.text = "SPEAK"

func callPause(iIn):
	bPausing = true
	await get_tree().create_timer(iIn).timeout
	bPausing = false

func callSpeak():
	if aTxt.size() > 0:
		if aTxt[iC] == "P5":
			callPause(0.5)
		elif aTxt[iC] == "P1":
			callPause(0.1)
		else:
			if not TTS.is_speaking():
				get_tree().get_root().get_node("TTS").speak(aTxt[iC])

		iC += 1

		if iC == aTxt.size():
			aTxt = []
			iC = -1
